circleci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -14,9 +14,9 @@ jobs:
       # documented at https://circleci.com/docs/2.0/circleci-images/
       # - image: circleci/postgres:9.4
       
-      - image: circleci/postgres:9.6.2-alpine
-        environment:
-          POSTGRES_USER: postgres
+      # - image: circleci/postgres:9.6.2-alpine
+      #   environment:
+      #     POSTGRES_USER: postgres
 
     working_directory: ~/repo
 
@@ -41,16 +41,16 @@ jobs:
           key: v1-dependencies-{{ checksum "Gemfile.lock" }}
         
       # Database setup
-      - run:
-          name: Waiting for PostgreSQL to start
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z localhost 5432 && echo Success && exit 0
-              echo -n .
-              sleep 2
-            done
-            echo Failed waiting for Postgres && exit 1
+      # - run:
+      #     name: Waiting for PostgreSQL to start
+      #     command: |
+      #       for i in `seq 1 10`;
+      #       do
+      #         nc -z localhost 5432 && echo Success && exit 0
+      #         echo -n .
+      #         sleep 2
+      #       done
+      #       echo Failed waiting for Postgres && exit 1
 
       - run: bundle exec rake db:create
       - run: bundle exec rake db:schema:load
